# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 lituus-lab
"""Python bindings for the UniVector vector-graphics engine."""
from ._core import (
    version,
    abi_version,
    init,
    strerror,
    is_relative,
    parameter_count,
    quad_point,
    cubic_point,
    compute_bounds,
    Path,
    PreparedPath,
    Image,
    Color,
    WINDING_NON_ZERO,
    WINDING_EVEN_ODD,
    FLATTEN_TOLERANCE,
    MAX_FLATTEN_DEPTH,
    MAX_FLATTEN_SEGMENTS,
    SUPERSAMPLE,
    GEOMETRIC_EPSILON,
    BLEND_NORMAL,
    BLEND_OVERWRITE,
    PATH_CLOSE,
    PATH_MOVE,
    PATH_LINE,
    PATH_HLINE,
    PATH_VLINE,
    PATH_CUBIC,
    PATH_SMOOTH_CUBIC,
    PATH_QUADRATIC,
    PATH_SMOOTH_QUADRATIC,
    PATH_ARC,
    PATH_REL_MOVE,
    PATH_REL_LINE,
    PATH_REL_HLINE,
    PATH_REL_VLINE,
    PATH_REL_CUBIC,
    PATH_REL_SMOOTH_CUBIC,
    PATH_REL_QUADRATIC,
    PATH_REL_SMOOTH_QUADRATIC,
    PATH_REL_ARC,
)

init()

__version__ = version()

__all__ = [
    "BLEND_NORMAL",
    "BLEND_OVERWRITE",
    "Color",
    "FLATTEN_TOLERANCE",
    "GEOMETRIC_EPSILON",
    "Image",
    "MAX_FLATTEN_DEPTH",
    "MAX_FLATTEN_SEGMENTS",
    "PATH_ARC",
    "PATH_CLOSE",
    "PATH_CUBIC",
    "PATH_HLINE",
    "PATH_LINE",
    "PATH_MOVE",
    "PATH_QUADRATIC",
    "PATH_REL_ARC",
    "PATH_REL_CUBIC",
    "PATH_REL_HLINE",
    "PATH_REL_LINE",
    "PATH_REL_MOVE",
    "PATH_REL_QUADRATIC",
    "PATH_REL_SMOOTH_CUBIC",
    "PATH_REL_SMOOTH_QUADRATIC",
    "PATH_REL_VLINE",
    "PATH_SMOOTH_CUBIC",
    "PATH_SMOOTH_QUADRATIC",
    "PATH_VLINE",
    "Path",
    "PreparedPath",
    "SUPERSAMPLE",
    "WINDING_EVEN_ODD",
    "WINDING_NON_ZERO",
    "__version__",
    "abi_version",
    "compute_bounds",
    "cubic_point",
    "init",
    "is_relative",
    "parameter_count",
    "quad_point",
    "strerror",
    "version",
]
